### ISSUE TITLE
attributes do not show up in completion list

### ISSUE THREAD

**Issue by nleclercq** [tango-controls/itango#11]
Hi gurus,
The device attributes do not show up anymore in the completion list. As far I remember properly they used to visible in the popup completion list. 

`t = TangoTest('sys/tg_test/1')`
`t.<tab>`

**Comment by vxgmichel** [comment]
Thanks for your report, it seems it either depends on the python or IPython version:
- **Python 3.4.3, IPython 4.2.1**: the attribute list does not appear
- **Python 2.7.5, IPython 3.2.1**: the attribute list does appear
What's your config?

**Comment by nleclercq** [comment]
Python 3.5.2 & IPython 5.1.0

**Comment by vxgmichel** [comment]
I found the culprit: ipython/ipython#8081

This means attribute completion is broken since **IPython 4.0.0**.

This issue can easily be solved by renaming the `DeviceProxy._getAttributeNames()` method as `DeviceProxy.__dir__`. I'm opening an issue on the pytango tracker.

**Comment by vxgmichel** [comment]
@nleclercq Thanks for the report!
