### ISSUE TITLE
read attribute callback (or hook)

### ISSUE THREAD

**Issue by nleclercq** [tango-controls/itango#12]
Hi,

It could be great to provide the users with a way to extend the itango features.  For instance, offering the ability to specify an "optional read attribute callback (or hook)" would allow to customize the behavior of a itango `<device-name>.<attribute-name>` command. The main targeted applications are: sophisticated printing, advanced plotting with user's preferred framework (matplotlib, Taurus, bokeh, ...) or specific error handling (see attached pict).

A coarse spec would define the pseudo-signature of the callback  as follow:

### `def read_attribute_hook (*args, **kwargs)`

**Parameters**:
- **dev**: the Tango device name (required cause the raw Tango attribute value does not contain it) 
- **attr**: the raw Tango attribute value (as return by `PyTango.DeviceProxy.read_attribute`) 
- **err**: exception thrown by the Tango layer in case the attribute reading failed
- **return**: anything different to "None" if the callback implementation fully took the display or error handing in charge and does not require the itango  (i.e. default) implementation to do anything. In this case the  itango implementation is supposed to transparently propagate the reference returned by the user defined callback to the caller.  Return None otherwise (i.e. ask itango to apply default behavior).

The same idea could be applied to the execution of commands.

![capture d ecran 2016-12-14 a 08 13 15](https://cloud.githubusercontent.com/assets/19185982/21174782/786f944a-c1df-11e6-8298-3921df2fec9b.png)

**Comment by nleclercq** [comment]
I just discovered that the `<device-name>.<attribute-name>` come from PyTango not itango. That fact ruins my proposal. Unless, you gurus, have an idea...

**Comment by vxgmichel** [comment]
What's the problem with the explicit approach?

```python
%pylab notebook
tt = TangoTest('sys/tg_test/1')
plot(tt.double_spectrum)
```

**Comment by nleclercq** [comment]
It's too explicit! :-)
I just would like to be able to control the behavior the <device-name>.<attribute-name> commands.
Anyway...

**Comment by vxgmichel** [comment]
I don't think it makes sense to get rid of the `plot` function since plotting usually requires parameters. However, it might be nice to have a specific formatter for `DeviceAttribute`:

```
ITango [5]: tt.read_attribute('long_scalar')
# => display value, quality, time stamp and data type in a readable manner
```
```

**Comment by nleclercq** [comment]
> I don't think it makes sense to get rid of the plot 
It was not the idea in fact. Anyway, I'm writing a magic to mimic what I'd like.

BTW, making some of itango function (officially) public would really help (i.e. would avoid a big wheel reinvention). Things like the following functions could migrate to a `itango.utils` module:
- __[DeviceProxy, AttributeProxy, ...]_completer
- __get_device_proxy
- any useful for

**Comment by nleclercq** [comment]
> However, it might be nice to have a specific formatter for DeviceAttribute
An explicit call `tt.read_attribute` already does  something like this.
![capture d ecran 2016-12-14 a 15 31 30](https://cloud.githubusercontent.com/assets/19185982/21185799/6f999c7a-c212-11e6-999c-0f70bf00fa8d.png)

**Comment by vxgmichel** [comment]
@nleclercq 
> An explicit call `tt.read_attribute` already does something like this.

Oh great! I only tried that in an IPython console, didn't know we had such a feature for Jupyter.

Anyway, feel free to make a PR for `itango.utils` and the plot command ;)
