### ISSUE TITLE
itango license

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/itango#17]
Hi guys,
reading the repositories of tango-controls, I've noticed there no license is specified here.
I wondered what is the license applied to this soft? Is it GPL?
Happy new year:)

**Comment by ajoubertza** [comment]
Hi @PhilLAL (2 years late!)

From the `setup.py` file, it is LGPL.  The itango project used to be part of pytango so it should use the same license:   LGPL-3.0. 
Feel free to submit a PR with a [license file](https://github.com/tango-controls/pytango/blob/develop/LICENSE.txt) taken from pytango.
