### ISSUE TITLE
Publish version 0.1.7 to PyPI

### ISSUE THREAD

**Issue by beenje** [tango-controls/itango#21]
I noticed that version 0.1.7 isn't on PyPI: https://pypi.org/project/itango/#history (latest version is 0.1.6)
Is it possible to publish it there?

**Comment by ajoubertza** [comment]
Hi @beenje.  This packages doesn't have an active maintainer.  If you'd like to do the work of publishing it, I can add you to the project on PyPI.  Do you want to volunteer?

**Comment by beenje** [comment]
OK. I can volunteer :-)
I have an account with the same username on PyPI.

**Comment by ajoubertza** [comment]
Thanks!  I've added you - on PyPI, and on GitHub (tango-controls).

**Comment by beenje** [comment]
Thanks! I have accepted both invitations.

Regarding the push to PyPI, I think it should be done by CI. I think I'll wait for the move to GitLab for that.

**Comment by beenje** [comment]
As there are other commits after the `v0.1.7` tag, I uploaded that version manually:

```
git checkout v0.1.7
docker run --rm -it -v $(pwd):/build python:3.6 bash
cd /build
python setup.py sdist bdist_wheel
pip install twine
twine upload dist/*
```

Closing this issue. Will create a new one to add ci for new release.
